/******************************************************************************************************

This file is automatically generated.
This file "Sql1718953631341VO.java" is part of project <"just write what you want"> , which is belong to Michael Pang (It's Me).
In my license, all codes can be shared free of charge. 
However, if it is used for commercial purposes, I need to be notified.
Here is my email "pangdongcan@live.com"

Copyright (c) 2024 Michael Pang.

*******************************************************************************************************/
package net.mickarea.tools.testcodes.dbtest.oracle11.beans.vo;

import net.mickarea.tools.annotation.MyColumn;
import net.mickarea.tools.annotation.MyIdGroup;
import net.mickarea.tools.annotation.MyVirtualEntity;
import net.mickarea.tools.utils.Stdout;

/**
 * 一个普通的 java bean 类
 * @author Michael Pang (Dongcan Pang)
 * @version 1.0
 * @since 2024年6月21日
 */
@MyVirtualEntity
public class TestOrclDataTypeVO {

	@MyIdGroup
    @MyColumn(name="seq_no", displayName="", extProperty="")
    private String seqNo;

    @MyColumn(name="cname", displayName="", extProperty="")
    private String cname;

    @MyColumn(name="app_date", displayName="", extProperty="")
    private java.sql.Timestamp appDate;

    @MyColumn(name="v_year", displayName="", extProperty="")
    private java.sql.Timestamp vYear;

    @MyColumn(name="v_month", displayName="", extProperty="")
    private java.sql.Timestamp vMonth;

    @MyColumn(name="v_day", displayName="", extProperty="")
    private java.sql.Timestamp vDay;

    @MyColumn(name="app_datetime_1", displayName="", extProperty="")
    private java.sql.Timestamp appDatetime1;

    @MyColumn(name="app_datetime_2", displayName="", extProperty="")
    private java.sql.Timestamp appDatetime2;

    @MyColumn(name="content", displayName="", extProperty="")
    private String content;

    @MyColumn(name="v_row2", displayName="", extProperty="")
    private String vRow2;

    @MyColumn(name="v_clob", displayName="", extProperty="")
    private String vClob;

    @MyColumn(name="v_nclob", displayName="", extProperty="")
    private String vNclob;

    @MyColumn(name="v_blob", displayName="", extProperty="")
    private byte[] vBlob;

    @MyColumn(name="v_nvarchar2", displayName="", extProperty="")
    private String vNvarchar2;

    @MyColumn(name="v_char", displayName="", extProperty="")
    private String vChar;

    @MyColumn(name="v_raw", displayName="", extProperty="")
    private byte[] vRaw;

    @MyColumn(name="v_float", displayName="", extProperty="")
    private Double vFloat;

    @MyColumn(name="v_int", displayName="", extProperty="")
    private java.math.BigDecimal vInt;

    @MyColumn(name="v_long", displayName="", extProperty="")
    private String vLong;

    @MyColumn(name="v_num_1", displayName="", extProperty="")
    private java.math.BigDecimal vNum1;

    @MyColumn(name="v_num_2", displayName="", extProperty="")
    private java.math.BigDecimal vNum2;

    @MyColumn(name="my_float", displayName="", extProperty="")
    private Double myFloat;

    @MyColumn(name="my_float_2", displayName="", extProperty="")
    private Double myFloat2;

    /**
     * >> 构造函数
     */
    public TestOrclDataTypeVO() {
        // TODO Auto-generated constructor stub
    }
    public TestOrclDataTypeVO(String seqNo, String cname, java.sql.Timestamp appDate, java.sql.Timestamp vYear, java.sql.Timestamp vMonth, java.sql.Timestamp vDay, java.sql.Timestamp appDatetime1, java.sql.Timestamp appDatetime2, String content, String vRow2, String vClob, String vNclob, byte[] vBlob, String vNvarchar2, String vChar, byte[] vRaw, Double vFloat, java.math.BigDecimal vInt, String vLong, java.math.BigDecimal vNum1, java.math.BigDecimal vNum2, Double myFloat, Double myFloat2) {
        this.seqNo=seqNo;
        this.cname=cname;
        this.appDate=appDate;
        this.vYear=vYear;
        this.vMonth=vMonth;
        this.vDay=vDay;
        this.appDatetime1=appDatetime1;
        this.appDatetime2=appDatetime2;
        this.content=content;
        this.vRow2=vRow2;
        this.vClob=vClob;
        this.vNclob=vNclob;
        this.vBlob=vBlob;
        this.vNvarchar2=vNvarchar2;
        this.vChar=vChar;
        this.vRaw=vRaw;
        this.vFloat=vFloat;
        this.vInt=vInt;
        this.vLong=vLong;
        this.vNum1=vNum1;
        this.vNum2=vNum2;
        this.myFloat=myFloat;
        this.myFloat2=myFloat2;
    }

    // getter and setter
    public String getSeqNo() {
        return seqNo;
    }
    public void setSeqNo(String seqNo) {
        this.seqNo=seqNo;
    }
    public String getCname() {
        return cname;
    }
    public void setCname(String cname) {
        this.cname=cname;
    }
    public java.sql.Timestamp getAppDate() {
        return appDate;
    }
    public void setAppDate(java.sql.Timestamp appDate) {
        this.appDate=appDate;
    }
    public java.sql.Timestamp getVYear() {
        return vYear;
    }
    public void setVYear(java.sql.Timestamp vYear) {
        this.vYear=vYear;
    }
    public java.sql.Timestamp getVMonth() {
        return vMonth;
    }
    public void setVMonth(java.sql.Timestamp vMonth) {
        this.vMonth=vMonth;
    }
    public java.sql.Timestamp getVDay() {
        return vDay;
    }
    public void setVDay(java.sql.Timestamp vDay) {
        this.vDay=vDay;
    }
    public java.sql.Timestamp getAppDatetime1() {
        return appDatetime1;
    }
    public void setAppDatetime1(java.sql.Timestamp appDatetime1) {
        this.appDatetime1=appDatetime1;
    }
    public java.sql.Timestamp getAppDatetime2() {
        return appDatetime2;
    }
    public void setAppDatetime2(java.sql.Timestamp appDatetime2) {
        this.appDatetime2=appDatetime2;
    }
    public String getContent() {
        return content;
    }
    public void setContent(String content) {
        this.content=content;
    }
    public String getVRow2() {
        return vRow2;
    }
    public void setVRow2(String vRow2) {
        this.vRow2=vRow2;
    }
    public String getVClob() {
        return vClob;
    }
    public void setVClob(String vClob) {
        this.vClob=vClob;
    }
    public String getVNclob() {
        return vNclob;
    }
    public void setVNclob(String vNclob) {
        this.vNclob=vNclob;
    }
    public byte[] getVBlob() {
        return vBlob;
    }
    public void setVBlob(byte[] vBlob) {
        this.vBlob=vBlob;
    }
    public String getVNvarchar2() {
        return vNvarchar2;
    }
    public void setVNvarchar2(String vNvarchar2) {
        this.vNvarchar2=vNvarchar2;
    }
    public String getVChar() {
        return vChar;
    }
    public void setVChar(String vChar) {
        this.vChar=vChar;
    }
    public byte[] getVRaw() {
        return vRaw;
    }
    public void setVRaw(byte[] vRaw) {
        this.vRaw=vRaw;
    }
    public Double getVFloat() {
        return vFloat;
    }
    public void setVFloat(Double vFloat) {
        this.vFloat=vFloat;
    }
    public java.math.BigDecimal getVInt() {
        return vInt;
    }
    public void setVInt(java.math.BigDecimal vInt) {
        this.vInt=vInt;
    }
    public String getVLong() {
        return vLong;
    }
    public void setVLong(String vLong) {
        this.vLong=vLong;
    }
    public java.math.BigDecimal getVNum1() {
        return vNum1;
    }
    public void setVNum1(java.math.BigDecimal vNum1) {
        this.vNum1=vNum1;
    }
    public java.math.BigDecimal getVNum2() {
        return vNum2;
    }
    public void setVNum2(java.math.BigDecimal vNum2) {
        this.vNum2=vNum2;
    }
    public Double getMyFloat() {
        return myFloat;
    }
    public void setMyFloat(Double myFloat) {
        this.myFloat=myFloat;
    }
    public Double getMyFloat2() {
        return myFloat2;
    }
    public void setMyFloat2(Double myFloat2) {
        this.myFloat2=myFloat2;
    }

    @Override
    public String toString() {
        String s = "Sql1718953631341VO{seqNo:%s, cname:%s, appDate:%s, vYear:%s, vMonth:%s, vDay:%s, appDatetime1:%s, appDatetime2:%s, content:%s, vRow2:%s, vClob:%s, vNclob:%s, vBlob:%s, vNvarchar2:%s, vChar:%s, vRaw:%s, vFloat:%s, vInt:%s, vLong:%s, vNum1:%s, vNum2:%s, myFloat:%s, myFloat2:%s}";
        return Stdout.fplToAnyWhere(s, this.seqNo, this.cname, this.appDate, this.vYear, this.vMonth, this.vDay, this.appDatetime1, this.appDatetime2, this.content, this.vRow2, this.vClob, this.vNclob, this.vBlob, this.vNvarchar2, this.vChar, this.vRaw, this.vFloat, this.vInt, this.vLong, this.vNum1, this.vNum2, this.myFloat, this.myFloat2);
    }
}
